### ISSUE TITLE
Use specific exception on delete_product

### ISSUE THREAD

**Issue by yftacherzog** [redhat-beyond/BuyTogether#37]
`delete_product` is using broad exception (`except Exception`). This will make us ignore all failures there, which is seldom what we're after.

The exception needs to change so we ignore only the specific exception that is raised when we try to delete a non-existing element.

**Comment by thetaxas2468** [comment]
I have updated it

**Comment by yftacherzog** [comment]
@thetaxas2468 make it a point to have a single PR fix a single issue. The smaller we make a PR, the easier is to get it reviewed and merged.
