### ISSUE TITLE
Clarify the query `q=` in the index function

### ISSUE THREAD

**Issue by yftacherzog** [redhat-beyond/BuyTogether#39]
The product's index function is using a query which needs to be clarified.

**Comment by thetaxas2468** [comment]
Django uses request and response objects to pass state through the system.

When a page is requested, Django creates an [HttpRequest object that contains metadata about the request. Then Django loads the appropriate view, passing the [HttpRequest] as the first argument to the view function. Each view is responsible for returning an [HttpResponse] object.


HttpRequest.GET
A dictionary-like object containing all given HTTP GET parameters

for example :
request url = www.EXAMPLE.com/q=Apple&w=Fruit/

request.GET = QueryDict('q=Apple&w=Fruit')
<QueryDict: {'q': 'Apple', 'w': 'Fruit'}>
request.GET['q']=Apple

**Comment by yftacherzog** [comment]
cc @Omeramsc

**Comment by thetaxas2468** [comment]
Should i close this issue?

**Comment by yftacherzog** [comment]
We can close for now.

**Comment by yftacherzog** [comment]
closing as not planned
