### ISSUE TITLE
Fix custom_user

### ISSUE THREAD

**Issue by thetaxas2468** [redhat-beyond/BuyTogether#86]
I have :
fixed the migration files
fixed the order of the migration files
fixed the customuser
created the currect way of using the User from django
removed few functions that is not needed
removed few tests that is not needed because django User have created a tests for them already
changed few tests
fixed the migration tests
wrote a better way of testing and the order of saving that happend because of they change of the customuser
and few more.

**Comment by thetaxas2468** [comment]
![pass2](https://user-images.githubusercontent.com/81024607/211432673-8d43c9a2-eebc-43d4-ac4e-bf616b59fc7e.PNG)
![product](https://user-images.githubusercontent.com/81024607/211432676-12a95029-339a-4c66-9127-abbf7573ce55.PNG)
![supplier_product](https://user-images.githubusercontent.com/81024607/211432678-766731df-08d3-44cb-86ed-d8ebfa3b61fd.PNG)
![suppliers](https://user-images.githubusercontent.com/81024607/211432680-f21294d7-0ae1-42fe-9971-db7c8230fe5d.PNG)
![client](https://user-images.githubusercontent.com/81024607/211432683-f6a50164-fe55-4c2f-b50b-302f804c6ee8.PNG)
![deliverylocation](https://user-images.githubusercontent.com/81024607/211432684-6b177e8f-1693-4326-9363-1ceea8f2fd04.PNG)
![order_product](https://user-images.githubusercontent.com/81024607/211432685-a68ed643-6baa-4002-ba45-0e0fc4f0917c.PNG)
![pass1](https://user-images.githubusercontent.com/81024607/211432686-18ff31ec-a12f-41ec-a1b4-94e74d3f4ade.PNG)

**Comment by nofaralfasi** [comment]
@thetaxas2468 you are mentioning here too many things for just 1 issue. 
Some of the descriptions are not clear. For example, "fixed the migration files" - what are we fixing here?
Please divide your work in a way that makes it easy for us to review and test it. 
Also, that way if you need to revert some of your changes, it won't affect everything else you've worked on.

**Comment by thetaxas2468** [comment]
i couldnt because all of the things that changed depend one on another
